image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - clean

before_script:
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - pip install docker-compose
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" $CI_REGISTRY
  - docker info

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose run --rm app sh -c 'npm test -s'

clean:
  stage: clean
  script:
    - docker-compose stop
    - docker-compose down
    - docker-compose rm -f
