version: '2'
services:
  web:
    image: "registry.gitlab.com/ender/docker-nginx-node-sample:node-web-${COMMIT_ID}"
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    environment:
    - NODE_ENV=${NODE_ENV}
    ports:
    - '80:80'
  app:
    image: "registry.gitlab.com/ender/docker-nginx-node-sample:node-app-${COMMIT_ID}"
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    environment:
    - NODE_ENV=${NODE_ENV}
