version: '2'
services:
  web:
    image: brankol/node-web
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    environment:
    - NODE_ENV=${NODE_ENV}
    ports:
    - '80:80'
  app:
    image: brankol/node-app
    build:
      context: .
      dockerfile: ./.docker/node/Dockerfile
    environment:
    - NODE_ENV=${NODE_ENV}
